workflows:
  android-release:
    name: Lucia5 Android Release
    max_build_duration: 60
    environment:
      flutter: stable
      vars:
        OPENAI_API_KEY: $OPENAI_API_KEY
        ELEVENLABS_API_KEY: $ELEVENLABS_API_KEY
    scripts:
      - name: Get dependencies
        script: |
          flutter pub get
      - name: Build APK
        script: |
          flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
