name: lucia5
description: Lucia5 Ultra Premium Flutter Project
version: 1.0.0+1

environment:
  sdk: ">=2.20.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  flutter_tts: ^3.5.0
  lottie: ^2.3.0
  provider: ^6.0.0
  flutter_secure_storage: ^7.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/avatars/
    - assets/voices/
    - assets/animations/
    - assets/images/
